Resources:
  ScraperFeedBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: "Enabled"
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:*
            Topic:
              Ref: ScraperFeedCreatedTopic
  ScraperFeedCreatedTopic:
    Type: AWS::SNS::Topic
  ScraperFeedCreatedTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowBucketToPushNotificationEffect
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: "*"
      Topics:
        - Ref: ScraperFeedCreatedTopic
  ScraperFeedHandledTopic:
    Type: AWS::SNS::Topic
  PricingFeedHandledTopic:
    Type: AWS::SNS::Topic
  BookFeedHandledTopic:
    Type: AWS::SNS::Topic

Outputs:
  ScraperFeedCreatedTopic:
    Value:
      Ref: ScraperFeedCreatedTopic
  ScraperFeedHandledTopicArn:
    Value:
      Ref: ScraperFeedHandledTopic
    Export:
      Name: ${sls:stage}-ScraperFeedHandledTopicArn
  PricingFeedHandledTopic:
    Value:
      Ref: PricingFeedHandledTopic
    Export:
      Name: ${sls:stage}-PricingFeedHandledTopicArn
  BookFeedHandledTopicArn:
    Value:
      Ref: BookFeedHandledTopic
    Export:
      Name: ${sls:stage}-BookFeedHandledTopicArn
  ScraperFeedBucket:
    Value:
      Ref: ScraperFeedBucket
    Export:
      Name: ${sls:stage}-ScraperFeedBucket
  ScraperFeedBucketArn:
    Value:
      Fn::GetAtt:
        - ScraperFeedBucket
        - Arn
    Export:
      Name: ${sls:stage}-ScraperFeedBucketArn
