Resources:
  ScraperFeedBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: "Enabled"
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:*
            Topic:
              Ref: ScraperFeedCreatedTopic
  ScraperFeedCreatedTopic:
    Type: AWS::SNS::Topic
  ScraperFeedCreatedTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowBucketToPushNotificationEffect
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: "*"
      Topics:
        - Ref: ScraperFeedCreatedTopic

Outputs:
  ScraperFeedCreatedTopic:
    Value:
      Ref: ScraperFeedCreatedTopic
  ScraperFeedBucket:
    Value:
      Ref: ScraperFeedBucket
    Export:
      Name: ${self:provider.stage}-ScraperFeedBucket
  ScraperFeedBucketArn:
    Value:
      Fn::GetAtt:
        - ScraperFeedBucket
        - Arn
    Export:
      Name: ${self:provider.stage}-ScraperFeedBucketArn
