service: node-express-read-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: ${self:custom.vars.stage, "dev"}
  logRetentionInDays: ${self:custom.vars.logRetentionInDays, 1}
  profile: serverless-grocery-admin
  memorySize: 512
  versionFunctions: false
  apiGateway:
    minimumCompressionSize: 1024

  environment:
    MONGO_URI: ${self:custom.vars.MONGO_URI}
    MONGO_DATABASE: ${self:custom.vars.MONGO_DATABASE}
    NHOST_JWT_SECRET: ${self:custom.vars.NHOST_JWT_SECRET}
    SENTRY_DSN: ${self:custom.vars.SENTRY_DSN}
    SENTRY_ENVIRONMENT: ${self:custom.vars.stage, "dev"}
    STAGE: ${self:custom.vars.stage, "dev"}

functions:
  api:
    handler: dist/server.handler
    timeout: 30
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: /{proxy+}
          cors: true
  api-url:
    handler: dist/server.handler
    timeout: 30
    disableLogs: true
    url:
      cors: true

package:
  artifact: artifact.zip

plugins:
  - serverless-offline

custom:
  vars: ${file(./sls-config.js)}
