service: node-express-read-api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${self:custom.vars.stage, "dev"}
  logRetentionInDays: ${self:custom.vars.logRetentionInDays, 1}
  profile: serverless-grocery-admin

  environment:
    MONGO_URI: ${env:MONGO_URI}
    MONGO_DATABASE: ${env:MONGO_DATABASE}

functions:
  api:
    handler: dist/server.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: /{proxy+}
          cors: true

package:
  include:
    - dist/**
    - node_modules/**
    - .env.example
  exclude:
    - ./**

plugins:
  - serverless-offline

custom:
  vars: ${file(./sls-config.js)}
