service: node-express-read-api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${self:custom.vars.stage, "dev"}
  logRetentionInDays: ${self:custom.vars.logRetentionInDays, 1}
  profile: serverless-grocery-admin
  memorySize: 512
  apiGateway:
    minimumCompressionSize: 1024

  environment:
    MONGO_URI: ${env:MONGO_URI}
    MONGO_DATABASE: ${env:MONGO_DATABASE}
    ELASTIC_API_KEY: ${env:ELASTIC_API_KEY}
    ELASTIC_URL: ${env:ELASTIC_URL}
    STAGE: ${self:custom.vars.stage, "dev"}

functions:
  api:
    handler: dist/server.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: /{proxy+}
          cors: true

package:
  artifact: artifact.zip

plugins:
  - serverless-offline

custom:
  vars: ${file(./sls-config.js)}
