service: node-express-read-api
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${self:custom.vars.stage, "dev"}
  logRetentionInDays: ${self:custom.vars.logRetentionInDays, 1}
  profile: serverless-grocery-admin
  memorySize: 512
  versionFunctions: false
  apiGateway:
    minimumCompressionSize: 1024

  environment:
    MONGO_URI: ${self:custom.vars.MONGO_URI}
    MONGO_DATABASE: ${self:custom.vars.MONGO_DATABASE}
    #ELASTIC_API_KEY: ${self:custom.vars.ELASTIC_API_KEY}
    #ELASTIC_URL: ${self:custom.vars.ELASTIC_URL}
    SENTRY_DSN: ${self:custom.vars.SENTRY_DSN}
    SENTRY_ENVIRONMENT: ${self:custom.vars.stage, "dev"}
    STAGE: ${self:custom.vars.stage, "dev"}

functions:
  api:
    handler: dist/server.handler
    timeout: 16
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: /{proxy+}
          cors: true

package:
  artifact: artifact.zip

plugins:
  - serverless-offline

custom:
  vars: ${file(./sls-config.js)}
