services:
  fastify-api:
    image: 'ewr.vultrcr.com/vikfandvultryregistry/mpn-fastify-app:latest'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      STAGE: dev
    networks:
      - traefik-public
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:3000/healthz || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.api-mpn_dev.rule=Host(`${API_DOMAIN}`)
        - traefik.http.routers.api-mpn_dev.entrypoints=https
        - traefik.http.routers.api-mpn_dev.tls.certresolver=letsencrypt
        - traefik.http.services.api-mpn_dev.loadbalancer.server.port=3000
  
networks:
  traefik-public:
    external: true
    name: traefik-public
  