# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: node-mpn-functions # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${self:custom.vars.stage, "dev"}
  logRetentionInDays: ${self:custom.vars.logRetentionInDays, 1}
  profile: serverless-mpn-admin
  timeout: 900
  memorySize: 1024

  environment:
    MONGO_URI: ${env:MONGO_URI}
    BUCKET_NAME: !ImportValue StaticAssetsBucket
    CLOUD_FRONT_DISTRIBUTION_ID: !ImportValue StaticAssetsDistribution
    STAGE: ${self:provider.stage}
    NODE_ENV: ${env:NODE_ENV}
    ELASTIC_URL: ${env:ELASTIC_URL}
    ELASTIC_API_KEY: ${env:ELASTIC_API_KEY}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: !Sub
        - "#{BucketArn}/*"
        - BucketArn: !ImportValue StaticAssetsBucketArn
    - Effect: "Allow"
      Action:
        - "cloudfront:CreateInvalidation"
      Resource: !Sub
        - "arn:aws:cloudfront::#{AccountId}:distribution/#{DistributionId}"
        - AccountId: !Ref "AWS::AccountId"
          DistributionId: !ImportValue StaticAssetsDistribution
functions:
  processGroceryOffers:
    handler: tokens/handler.processGroceryOffers
    events:
      - schedule:
          rate: cron(0 7 ? * MON *) # Every Monday 07:00 AM
          input:
            mongoCollection: "byggoffers"
      - schedule:
          rate: cron(0 7 ? * MON *) # Every Monday 07:00 AM
          input:
            mongoCollection: "sebyggoffers"
      - schedule:
          rate: cron(0 7 ? * MON *) # Every Monday 07:00 AM
          input:
            mongoCollection: "segroceryoffers"
      - schedule:
          rate: cron(0 7 ? * MON *) # Every Monday 07:00 AM
          input:
            mongoCollection: "herbvuoffers"
      - schedule:
          rate: cron(0 7 ? * MON *) # Every Monday 07:00 AM
          input:
            mongoCollection: "groceryoffers"

  deleteOffersFromElastic:
    handler: elastic/handler.handleTriggerDeleteEvent
    events:
      - schedule:
          rate: rate(55 minutes)
          input:
            engineName: byggoffers
      - schedule:
          rate: rate(110 minutes)
          input:
            engineName: groceryoffers
      - schedule:
          rate: rate(125 minutes)
          input:
            engineName: segroceryoffers
      - schedule:
          rate: rate(65 minutes)
          input:
            engineName: sebyggoffers
      - schedule:
          rate: rate(45 minutes)
          input:
            engineName: extraoffers

  migrateOffersToElastic:
    handler: elastic/handler.handleTriggerMigrateEvent
  migrateOffersToElasticSns:
    handler: elastic/handler.handleSnsMigrateEvent
    events:
      - sns:
          topicName: ScraperFeedHandled
          arn:
            Fn::ImportValue: !Sub
              - "#{Stage}-ScraperFeedHandledTopicArn"
              - Stage: ${self:provider.stage}

  handlePageViewsFeed:
    handler: stats/handler.handleFeed
    events:
      - http: PUT pageviews

  processGroceryOffersSns:
    handler: tokens/handler.processGroceryOffersSns
    events:
      - sns:
          topicName: ScraperFeedHandled
          arn:
            Fn::ImportValue: !Sub
              - "#{Stage}-ScraperFeedHandledTopicArn"
              - Stage: ${self:provider.stage}

plugins:
  - serverless-cloudformation-sub-variables

custom:
  vars: ${file(./sls-config.js)}
