org: matpanett
app: node-mpn-functions

service: node-mpn-functions 
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  logRetentionInDays: ${self:custom.logRetentionInDays.${sls:stage}, self:custom.logRetentionInDays.other}
  profile: serverless-mpn-admin
  timeout: 900
  memorySize: 2048
  versionFunctions: false

  environment:
    STAGE: ${sls:stage}
    NODE_ENV: ${env:NODE_ENV}
    SENTRY_DSN: ${env:SENTRY_DSN}
    SENTRY_ENVIRONMENT: ${sls:stage}
    NHOST_ADMIN_SECRET: ${env:NHOST_ADMIN_SECRET}
    JWT_SECRET: ${env:JWT_SECRET}
    SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}
    ENDPOINT_URL: !Sub
      - "https://#{ApiId}.execute-api.#{AWS::Region}.#{AWS::URLSuffix}"
      - ApiId: !Ref "HttpApi"

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"
    
functions:
  handleOffersForNotificationsSns:
    handler: offer-notifications/handle-offers.handlerSns
    events:
      - sns:
          topicName: ScraperFeedHandled
          arn:
            Fn::ImportValue: !Sub
              - "#{Stage}-PricingFeedHandledTopicArn"
              - Stage: ${sls:stage}
  handleOffersForNotificationsTrigger:
    handler: offer-notifications/handle-offers.handlerTrigger
  unsubscribeEvents:
    handler: offer-notifications/unsubscribe.handle
    timeout: 30
    events:
      - httpApi: "GET /unsubscribe"
plugins:
  - serverless-cloudformation-sub-variables
  - serverless-offline
  - serverless-esbuild

custom:
  logRetentionInDays:
    prod: 30
    other: 1
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: node20
    define:
      "require.resolve": undefined
    platform: node
    concurrency: 10

       
