# Use the official Python 3.12 image as the base
FROM python:3.11

# Install cron
RUN apt-get update && apt-get install -y cron


# Set environment variables to avoid writing .pyc files and to avoid buffering
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Copy requirements and install them
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the entire project to the working directory
COPY . /app/

CMD cron -f
